version: '3'
services:

  mongodb:
    image: mongo
    command: mongod --port 27017 
    ports:
      - '27017:27017'
    networks:
      - default
      - net

  server:
    image: cheerfy:latest 
    ports:
      - 9000:9000
    networks:
      - default
      - net
    links:
      - mongodb 

networks:
   net:
    external: true

